name: Build and Deploy to Github Pages

on:
  push:
    branches:
      - main  # Here source code branch is `master`, it could be other branch
  # schedule:
    # - cron:  '0 * * * *'

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository code
      - uses: actions/checkout@v2

      # Step 3: Setup Ruby 2.7 explicitly
      #- uses: ruby/setup-ruby@v1
      #  with:
      #    ruby-version: '2.7'  # Ensure Ruby 2.7 is used

      # Step 4: Install Bundler 2.4.22
      #- run: gem install bundler -v 2.4.22

      # Step 5: Cache dependencies to speed up future builds
      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      # Step 6: Install project dependencies with Bundler
      #- run: |
      #    bundle install --path vendor/bundle

      # Use GitHub Deploy Action to build and deploy to Github
      - uses: jeffreytse/jekyll-deploy-action@v0.3.0
        with:
          provider: 'github'
          token: ${{ secrets.GH_TOKEN }} # It's your Personal Access Token(PAT)
          repository: ''             # Default is current repository
          branch: 'gh-pages'         # Default is gh-pages for github provider
          jekyll_src: './'           # Default is root directory
          jekyll_cfg: '_config.yml'  # Default is _config.yml
          jekyll_baseurl: ''         # Default is according to _config.yml
          bundler_ver: '=2.4.22'     # latest bundler version has incompatible problem, use fix version instead
          cname: ''                  # Default is to not use a cname
          actor: ''                  # Default is the GITHUB_ACTOR
          pre_build_commands: ''     # Installing additional dependencies (Arch Linux)

      # Step 8: Clean up to avoid carrying over old states
      - run: |
          rm -rf vendor/bundle
          rm Gemfile.lock
